// jvmlib.cpp : This file contains the 'main' function. Program execution begins and ends there.
//

#include <iostream>

/* DO NOT EDIT THIS FILE - it is machine generated */
#ifdef _WIN32
#include "windows/jni.h"
#include "windows/jni_md.h"
#else
#include "linux/jni.h"
#include "linux/jni_md.h"
#endif

#ifdef __linux__
#include <unistd.h>
#include <stdlib.h>
#include <signal.h>
#include <time.h>
#include <errno.h>
#endif

#include <stdio.h>
#include <wchar.h>
#include <algorithm>
#include <utility>

int main()
{
    std::cout << "Hello World!\n";
}

// Run program: Ctrl + F5 or Debug > Start Without Debugging menu
// Debug program: F5 or Debug > Start Debugging menu

// Tips for Getting Started: 
//   1. Use the Solution Explorer window to add/manage files
//   2. Use the Team Explorer window to connect to source control
//   3. Use the Output window to see build output and other messages
//   4. Use the Error List window to view errors
//   5. Go to Project > Add New Item to create new code files, or Project > Add Existing Item to add existing code files to the project
//   6. In the future, to open this project again, go to File > Open > Project and select the .sln file
